/**
 * Angular.Schule Book API
 * Simple HTTP backend for serving books
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * An object with a rating value (1...5)
 */
export interface Rating { 
    /**
     * Rating value for a book from one star (bad) to five stars (great)
     */
    rating: number;
}
