/**
 * Angular.Schule Book API
 * Simple HTTP backend for serving books
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Link to an image, which is used as a thumbnail
 */
export interface Thumbnail { 
    /**
     * Image to display
     */
    url: string;
    /**
     * Caption of the image
     */
    title: string;
}
