/**
 * Contact Application API
 * This is a sample Spring Boot RESTful service using springdoc-openapi and OpenAPI 3.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Account { 
    id?: number;
    email?: string;
    username?: string;
    firstName?: string;
    lastName?: string;
    points?: number;
    roles?: Array<Account.RolesEnum>;
    active?: boolean;
}
export namespace Account {
    export type RolesEnum = 'USER' | 'MOD' | 'ADMIN';
    export const RolesEnum = {
        USER: 'USER' as RolesEnum,
        MOD: 'MOD' as RolesEnum,
        ADMIN: 'ADMIN' as RolesEnum
    };
}