/*
 * Angular.Schule Book API
 * Simple HTTP backend for serving books
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Link to an image, which is used as a thumbnail
 */
@ApiModel(description = "Link to an image, which is used as a thumbnail")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-10-19T14:43:14.233+07:00")
public class Thumbnail {
  @SerializedName("url")
  private String url = null;

  @SerializedName("title")
  private String title = null;

  public Thumbnail url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Image to display
   * @return url
  **/
  @ApiModelProperty(example = "https://api.angular.schule/images/cover/angular_auflage3.jpg", required = true, value = "Image to display")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Thumbnail title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Caption of the image
   * @return title
  **/
  @ApiModelProperty(example = "Front Cover", required = true, value = "Caption of the image")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Thumbnail thumbnail = (Thumbnail) o;
    return Objects.equals(this.url, thumbnail.url) &&
        Objects.equals(this.title, thumbnail.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Thumbnail {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

