/*
 * Angular.Schule Book API
 * Simple HTTP backend for serving books
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AvatarApi
 */
@Ignore
public class AvatarApiTest {

    private final AvatarApi api = new AvatarApi();

    
    /**
     * Get avatar image for number
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void avatarNumGetTest() throws ApiException {
        BigDecimal num = null;
        api.avatarNumGet(num);

        // TODO: test validations
    }
    
}
