/*
 * Angular.Schule Book API
 * Simple HTTP backend for serving books
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Book;
import io.swagger.client.model.RestError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BooksslowApi
 */
@Ignore
public class BooksslowApiTest {

    private final BooksslowApi api = new BooksslowApi();

    
    /**
     * Get a single book by ISBN, but with a 5s delay
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void booksIsbnSlowGetTest() throws ApiException {
        String isbn = null;
        Book response = api.booksIsbnSlowGet(isbn);

        // TODO: test validations
    }
    
    /**
     * Get all books, but with a 5s delay
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void booksSlowGetTest() throws ApiException {
        List<Book> response = api.booksSlowGet();

        // TODO: test validations
    }
    
}
