/**
 * Contact Application API
 * This is a sample Spring Boot RESTful service using springdoc-openapi and OpenAPI 3.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Account { 
    id?: number;
    email?: string;
    username?: string;
    firstName?: string;
    lastName?: string;
    points?: number;
    roles?: Array<Account.RolesEnum>;
    active?: boolean;
}
export namespace Account {
    export type RolesEnum = 'USER' | 'MOD' | 'ADMIN';
    export const RolesEnum = {
        User: 'USER' as RolesEnum,
        Mod: 'MOD' as RolesEnum,
        Admin: 'ADMIN' as RolesEnum
    };
}


