/**
 * Contact Application API
 * This is a sample Spring Boot RESTful service using springdoc-openapi and OpenAPI 3.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookCategory } from './bookCategory';


export interface Book { 
    id?: number;
    name?: string;
    author?: string;
    rate?: number;
    publishingDate?: string;
    charge?: boolean;
    price?: number;
    description?: string;
    view?: number;
    image?: string;
    bookCategory?: BookCategory;
}

